
import { Cliente, StatusCliente } from '../../types';

// Dados dos clientes com giro semanal e periodicidade
export const clientesComDados: Partial<Cliente>[] = [
  { nome: "AMPM (João Wallig)", quantidadePadrao: 15, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. Dr. João Wallig, 1800 - Passo da Areia, Porto Alegre - RS" },
  { nome: "Arena Sports Poa", quantidadePadrao: 15, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Bento Gonçalves, 567 - Partenon, Porto Alegre - RS" },
  { nome: "Argentum", quantidadePadrao: 50, periodicidadePadrao: 7, statusCliente: "Ativo", enderecoEntrega: "R. 24 de Outubro, 111 - Moinhos de Vento, Porto Alegre - RS" },
  { nome: "Armazém da Redenção", quantidadePadrao: 20, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. José Bonifácio, 675 - Farroupilha, Porto Alegre - RS" },
  { nome: "Armazém do Sabor", quantidadePadrao: 7, periodicidadePadrao: 14, statusCliente: "A ativar", enderecoEntrega: "R. Padre Chagas, 342 - Moinhos de Vento, Porto Alegre - RS" },
  { nome: "Bampi", quantidadePadrao: 5, periodicidadePadrao: 21, statusCliente: "Ativo", enderecoEntrega: "R. Silva Jardim, 408 - Auxiliadora, Porto Alegre - RS" },
  { nome: "Bendita Esquina", quantidadePadrao: 15, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Osvaldo Aranha, 960 - Bom Fim, Porto Alegre - RS" },
  { nome: "Boteco 787", quantidadePadrao: 15, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Protásio Alves, 787 - Rio Branco, Porto Alegre - RS" },
  { nome: "Bruno - Distribuidor", quantidadePadrao: 120, periodicidadePadrao: 14, statusCliente: "Em análise", enderecoEntrega: "Av. Assis Brasil, 3522 - São Sebastião, Porto Alegre - RS" },
  { nome: "Cafeína e Gasolina", quantidadePadrao: 30, periodicidadePadrao: 7, statusCliente: "Ativo", enderecoEntrega: "R. Barão do Triunfo, 440 - Azenha, Porto Alegre - RS" },
  { nome: "CASL", quantidadePadrao: 15, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. Ipiranga, 6681 - Partenon, Porto Alegre - RS" },
  { nome: "Cavanhas Barão", quantidadePadrao: 8, periodicidadePadrao: 21, statusCliente: "Standby", enderecoEntrega: "Av. Barão do Amazonas, 123 - São Geraldo, Porto Alegre - RS" },
  { nome: "CECIV UFRGS", quantidadePadrao: 25, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. Paulo Gama, 110 - Farroupilha, Porto Alegre - RS" },
  { nome: "Cestas POA", quantidadePadrao: 20, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "R. Ramiro Barcelos, 1450 - Rio Branco, Porto Alegre - RS" },
  { nome: "Chalet Suisse", quantidadePadrao: 20, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Goethe, 100 - Rio Branco, Porto Alegre - RS" },
  { nome: "Confraria do Café", quantidadePadrao: 15, periodicidadePadrao: 7, statusCliente: "Ativo", enderecoEntrega: "Av. Independência, 820 - Independência, Porto Alegre - RS" },
  { nome: "Curtir e Celebrar Cestas", quantidadePadrao: 5, periodicidadePadrao: 21, statusCliente: "Inativo", enderecoEntrega: "R. Gonçalo de Carvalho, 330 - Floresta, Porto Alegre - RS" },
  { nome: "DAEAMB", quantidadePadrao: 20, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. Bento Gonçalves, 9500 - Agronomia, Porto Alegre - RS" },
  { nome: "DAPROD UFRGS", quantidadePadrao: 30, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. Paulo Gama, 110 - Farroupilha, Porto Alegre - RS" },
  { nome: "DCE UFCSPA", quantidadePadrao: 208, periodicidadePadrao: 7, statusCliente: "Ativo", enderecoEntrega: "R. Sarmento Leite, 245 - Centro Histórico, Porto Alegre - RS" },
  { nome: "Demarchi", quantidadePadrao: 15, periodicidadePadrao: 21, statusCliente: "A ativar", enderecoEntrega: "Av. Cristóvão Colombo, 545 - Floresta, Porto Alegre - RS" },
  { nome: "Divino Verde", quantidadePadrao: 90, periodicidadePadrao: 7, statusCliente: "Ativo", enderecoEntrega: "R. Quintino Bocaiúva, 707 - Moinhos de Vento, Porto Alegre - RS" },
  { nome: "E.E.E.E.F Jerônimo de Alb.", quantidadePadrao: 10, periodicidadePadrao: 21, statusCliente: "Ativo", enderecoEntrega: "R. Jerônimo de Ornelas, 55 - Santana, Porto Alegre - RS" },
  { nome: "Engenho do Pão", quantidadePadrao: 30, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "R. Mariante, 288 - Rio Branco, Porto Alegre - RS" },
  { nome: "Eurostock Investimentos", quantidadePadrao: 30, periodicidadePadrao: 7, statusCliente: "Ativo", enderecoEntrega: "Av. Carlos Gomes, 300 - Auxiliadora, Porto Alegre - RS" },
  { nome: "Everest Pub", quantidadePadrao: 10, periodicidadePadrao: 28, statusCliente: "Ativo", enderecoEntrega: "R. Olavo Barreto Viana, 18 - Moinhos de Vento, Porto Alegre - RS" },
  { nome: "EWF Luta Livre", quantidadePadrao: 12, periodicidadePadrao: 28, statusCliente: "Ativo", enderecoEntrega: "R. Mostardeiro, 780 - Moinhos de Vento, Porto Alegre - RS" },
  { nome: "Giulia - Distribuidor", quantidadePadrao: 150, periodicidadePadrao: 3, statusCliente: "Ativo", enderecoEntrega: "Av. Borges de Medeiros, 2500 - Praia de Belas, Porto Alegre - RS" },
  { nome: "GL Assados", quantidadePadrao: 10, periodicidadePadrao: 28, statusCliente: "Standby", enderecoEntrega: "Av. Otto Niemeyer, 2500 - Cavalhada, Porto Alegre - RS" },
  { nome: "Guadalajara Formaturas", quantidadePadrao: 100, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Ipiranga, 5200 - Azenha, Porto Alegre - RS" },
  { nome: "La Mafia (João Wallig)", quantidadePadrao: 10, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. Dr. João Wallig, 1800 - Passo da Areia, Porto Alegre - RS" },
  { nome: "La Mafia (Petrópolis)", quantidadePadrao: 7, periodicidadePadrao: 21, statusCliente: "Ativo", enderecoEntrega: "R. Lavras, 400 - Petrópolis, Porto Alegre - RS" },
  { nome: "Limas Bar", quantidadePadrao: 10, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "R. Fernandes Vieira, 466 - Bom Fim, Porto Alegre - RS" },
  { nome: "Madri Padaria e Confeitaria", quantidadePadrao: 10, periodicidadePadrao: 21, statusCliente: "Ativo", enderecoEntrega: "Av. Cristóvão Colombo, 545 - Floresta, Porto Alegre - RS" },
  { nome: "MedCafé Fleming", quantidadePadrao: 15, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "R. Prof. Annes Dias, 295 - Centro Histórico, Porto Alegre - RS" },
  { nome: "Mercado Pinheiro", quantidadePadrao: 40, periodicidadePadrao: 7, statusCliente: "Ativo", enderecoEntrega: "Av. Venâncio Aires, 1060 - Azenha, Porto Alegre - RS" },
  { nome: "Mercado Santiago", quantidadePadrao: 20, periodicidadePadrao: 7, statusCliente: "Ativo", enderecoEntrega: "R. Santiago, 725 - São Geraldo, Porto Alegre - RS" },
  { nome: "Moita", quantidadePadrao: 30, periodicidadePadrao: 7, statusCliente: "Ativo", enderecoEntrega: "R. Padre Chagas, 314 - Moinhos de Vento, Porto Alegre - RS" },
  { nome: "Onii Soluções Autônomas", quantidadePadrao: 15, periodicidadePadrao: 28, statusCliente: "Ativo", enderecoEntrega: "Av. Ipiranga, 6681 - Partenon, Porto Alegre - RS" },
  { nome: "Panetteria", quantidadePadrao: 40, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Otto Niemeyer, 2565 - Camaquã, Porto Alegre - RS" },
  { nome: "Pé na Areia 1", quantidadePadrao: 20, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. Guaíba, 10435 - Ipanema, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Aeroporto)", quantidadePadrao: 15, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Severo Dullius, 90010 - Anchieta, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Anita)", quantidadePadrao: 18, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Anita Garibaldi, 1300 - Mont'Serrat, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Bela Vista)", quantidadePadrao: 40, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "R. Dr. Timóteo, 602 - Bela Vista, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Bento/Intercap)", quantidadePadrao: 15, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Bento Gonçalves, 8000 - Agronomia, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Brino)", quantidadePadrao: 15, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. Otto Niemeyer, 2500 - Cavalhada, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Carlos Gomes)", quantidadePadrao: 20, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Carlos Gomes, 281 - Auxiliadora, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Forte/Via Porto)", quantidadePadrao: 15, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Mauá, 1050 - Centro Histórico, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Moinhos)", quantidadePadrao: 15, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "R. Dinarte Ribeiro, 50 - Moinhos de Vento, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Painera)", quantidadePadrao: 20, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Protásio Alves, 1090 - Alto Petrópolis, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Planetário)", quantidadePadrao: 10, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. Ipiranga, 6000 - Partenon, Porto Alegre - RS" },
  { nome: "REDEVIP24H (Ramiro)", quantidadePadrao: 30, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "R. Ramiro Barcelos, 1954 - Rio Branco, Porto Alegre - RS" },
  { nome: "Refugios Bar e Restaurante", quantidadePadrao: 15, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Protásio Alves, 6999 - Alto Petrópolis, Porto Alegre - RS" },
  { nome: "Silva Lanches", quantidadePadrao: 10, periodicidadePadrao: 21, statusCliente: "Ativo", enderecoEntrega: "R. 24 de Outubro, 1222 - Moinhos de Vento, Porto Alegre - RS" },
  { nome: "Sirene Fish n Chips", quantidadePadrao: 15, periodicidadePadrao: 10, statusCliente: "Ativo", enderecoEntrega: "Av. Dr. Nilo Peçanha, 1851 - Três Figueiras, Porto Alegre - RS" },
  { nome: "Temperandus", quantidadePadrao: 10, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "R. Padre Chagas, 400 - Moinhos de Vento, Porto Alegre - RS" },
  { nome: "The Brothers Distribuidora", quantidadePadrao: 0, periodicidadePadrao: 7, statusCliente: "Em análise", enderecoEntrega: "R. Padre Chagas, 342 - Moinhos de Vento, Porto Alegre - RS" },
  { nome: "Xirú Beer", quantidadePadrao: 8, periodicidadePadrao: 14, statusCliente: "Ativo", enderecoEntrega: "Av. Dr. Nilo Peçanha, 2000 - Boa Vista, Porto Alegre - RS" }
];
